name: trajectory
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- pip
- patchelf
- pip:
    - -f https://download.pytorch.org/whl/torch_stable.html
    - numpy
    - wheel==0.38.4
    - setuptools==65.5.0
    - gym==0.20.0
    - matplotlib==3.3.4
    - torch==1.9.1+cu111
    - typed-argument-parser
    # - git+https://github.com/Farama-Foundation/d4rl@f2a05c0d66722499bf8031b094d9af3aea7c372b#egg=d4rl
    - scikit-image==0.17.2
    - scikit-video==1.1.11
    - gitpython
    - os
    - d3rlpy
    - pyclustering
    - moviepy
    - scipy
    - scikit-learn
