name: halfcheetah
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- pip
- patchelf
- pip:
    - -f https://download.pytorch.org/whl/torch_stable.html
    - gym==0.24.0
    - numpy
    - setuptools==65.5.0
    - matplotlib==3.3.4
    - torch==1.9.1+cu111
    - typed-argument-parser
    - scikit-image==0.17.2
    - scikit-video==1.1.11
    - wheel==0.38.4
    - d3rlpy==1.1.1
    - pyclustering
    - moviepy
    - scipy
    - scikit-learn
    - gitpython
    - cython<3
    - mujoco-py<2.2,>=2.1
    - git+https://github.com/Farama-Foundation/d4rl@f2a05c0d66722499bf8031b094d9af3aea7c372b#egg=d4rl
